- conf/tasks/frontend.js
- lib/editor-prompt.pug
- lib/history-prompt.pug
- lib/js/directives/ng-ace-editor.js
- lib/js/index.js
- lib/js/interface/left.js
- lib/js/npm/npm-operations.js
- lib/left.pug
- lib/scss/ace-editor.scss
- lib/scss/colors.scss
- lib/scss/footer.scss
- lib/scss/header.scss
- lib/scss/home.scss
- lib/scss/layout.scss
- lib/scss/prompt.scss
- lib/scss/settings.scss
- lib/scss/variables.scss
- lib/top.pug
- package.json
closes #16 https://github.com/720kb/ndm/issues/16
> Dev snapshots history

- lib/js/interface/shell.js
- lib/js/npm/npm-api.js
Updating code to use user instead of group (as that's what npm has you set) and look at npm prefix + /lib/node_modules instead of just the prefix as for some people the prefix is /usr/local which it appears most people do not "own".
See #42
> Fixing ndm for people who use /usr/local as their npm prefix

- lib/js/errors/errors.js
- lib/js/interface/left.js
- lib/js/npm/npm-api.js
- lib/js/npm/npm-operations.js
- lib/left.pug
- lib/scss/progress.scss
- lib/scss/variables.scss
They are working but need to be tested a little more!
- Right click  on project
- Run script 
- script 1
- script 2
- etc..
> npm run <script>

- lib/install-new-package.pug
- lib/js/directives/ng-tag-input.js
- lib/js/index.js
- lib/js/interface/top.js
- lib/scss/prompt.scss
- lib/scss/variables.scss
- lib/top.pug
> Install multiple packages in project

- README.md
Backers&Sponsors from your open collective will automatically appear on your readme. 
See for example: github.com/apex/apex#backers
[Here](https://github.com/opencollective/opencollective/wiki/Github-banner) is a link with more info.
> add backers&sponsors

- lib/index.pug
- lib/js/interface/left.js
- lib/left.pug
- lib/logs-prompt.pug
- lib/scss/loading.scss
- lib/scss/progress.scss
- lib/scss/win/win.scss
Ability to close/dismiss running scripts and context menu actions
> Dismiss contextmenu actions

- lib/editor-prompt.pug
- lib/history-prompt.pug
- lib/left.pug
- lib/logs-prompt.pug
- lib/scss/header.scss
- lib/scss/prompt.scss
bigger editor and logs and history
> New prompts

- lib/img/lock.svg
- lib/js/assets.js
- lib/js/interface/left.js
- lib/js/interface/shell.js
- lib/js/npm/npm-operations.js
- lib/left.pug
- lib/scss/layout.scss
- lib/scss/progress.scss
- npm-shrinkwrap.json
npm shrinkwrap for projects , closes #29
> npm shrinkwrap

- lib/content.pug
- lib/js/directives/ng-table-keyboard.js
- lib/js/index.js
> Ng table keyboard

- lib/install-new-package-version.pug
- lib/js/interface/content.js
- lib/js/interface/shell.js
- lib/scss/prompt.scss
- lib/scss/variables.scss
all pkg versions available in selectbox
in progress for #135 
Not yet ready
> Selectbox to show package versions (install latest prompt)

- lib/js/npm/npm-operations.js
> Fix for #137

- appveyor.yml
> Rename exe file

- README.md
- index.html
#WARNING
Marge ONLY when Windows release is available for download.
> Gh-pages for windows release

- .eslintrc
- .travis.yml
- README.md
- conf/tasks/es6-build.js
- conf/tasks/front-end.js
- index.js
- lib/js/index.js
- lib/js/update.js
- lib/scss/linux/index.scss
- lib/scss/loading.scss
- lib/scss/mac/index.scss
- lib/scss/updates.scss
- lib/scss/win/index.scss
- lib/update.pug
- menu.js
- package.json
> App Updater/ Updates

- lib/editor-prompt.pug
- lib/js/directives/ng-ace-editor.js
- lib/js/interface/left.js
Right click -> edit -> .npmrc
implemented. closes #35 
No global configs yet.
> Edit/create local .npmrc

- appveyor.yml
for https://github.com/720kb/ndm/issues/150
test: create a PR for gh-pages see if appveyor runs on it
> AppVeyor specific branch build only

- .travis.yml
- README.md
- conf/linux.sh
Linux updates are done via travis using [gemfury](https://gemfury.com/).
> Linux packages

- css/site.css
- index.html
we will merge this to show new linux informations 
cc @wouldgo
> Gh-pages for linux updates

- css/site.css
- index.html
> Revert "Gh-pages for linux updates"

- css/site.css
- index.html
Should be ok for next v1.1.1
Wait to merge until release is done.
> Gh-pages for next v1.1.1

- lib/footer.pug
- lib/js/interface/shell.js
- lib/npm-update-log.pug
Message box to confirm the globally npm update
> Update npm globally - confirm alert

- README.md
Merge when next tab-views release is deployed.
> [README] Next Readme screenshot for next release
